name: Deployment pipeline

on:
  push:
    branches:
      - main

  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - run: npm install

      - run: npm test

      - name: Deploy
        if: |
          github.event_name == 'push' &&
          !contains(join(github.event.commits.*.message), '#skip')

        run: echo "Deploy step"

  tag_release:
    needs: [simple_deployment_pipeline]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Bump version and push tag
        if: |
          github.event_name == 'push' &&
          !contains(join(github.event.commits.*.message), '#skip')

        uses: anothrNick/github-tag-action@1.75.0

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch